meta_site_name: "Compost Lyon"
meta_title: "Tout sur le compost à Lyon - Compost Lyon"
meta_description: "Tout sur le compost à Lyon"
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@CompostLyon"
